### ISSUE TITLE
Cannot trace model with torch.jit.trace

### ISSUE THREAD

**Issue by bonvinia** [TencentYoutuResearch/AnomalyDetection-SoftPatch#5]
Hi,

I created a SoftPatch anomaly detection model based on the code on your repository, I need to save the trained model using torch.jit.trace, but the tracing process results in the following error:

`[ CPUFloatType{340,340} ]) of traced region did not have observable data dependence with trace inputs; this probably indicates your program cannot be understood by the tracer.`

Have you ever tried to serialize the model with torch.jit.trace? 

Thank you in advance.

**Comment by 1amrutesh** [comment]
No, I have not tried that.

**Comment by jam-cc** [comment]
We have not tried using TORCH.JIT.TRACE to save models. I guess the problem you encountered may be caused by the memory bank module. There is no torch used to establish the memory bank in our code. Instead, we use faiss, which has both CPU and GPU versions.
