### ISSUE TITLE
There is a path error in the softpath.py

### ISSUE THREAD

**Issue by cjy513203427** [TencentYoutuResearch/AnomalyDetection-SoftPatch#6]
All the py file under src should add src.
For example: src.common, src.sampler, src.backbones.

Otherwise there would be "No Module Found Error".

**Comment by spa-yhson** [comment]
Appreciate your notice and sharing.
Other than that, I have encountered the following error from `main.py`

` 
  File "main.py", line 79, in get_dataloaders
    dataset_library = __import__(dataset_info[0], fromlist=[dataset_info[1]])
ModuleNotFoundError: No module named 'datasets'`

If you have solved the issue, your sharing of the solution would be greatly appreciated.

**Comment by yaoyaoyao13** [comment]
I'm having the same issue, but using your method didn't fix the problem.
